Swap Charting to Seaborn/Pandas
cdoern/takecareofourplants pull request #2
Opened 2021-03-19 20:38 UTC by jacobswe

Updates graph.py to use Pandas and Seaborn to plot weekly results. New method should be robust to the number of days (within reason), uses the subplots method to generate fig and axes for Seaborn. Dates parsed using Pandas.

Sample chart looks like this:
![image](https://user-images.githubusercontent.com/14115132/111839530-50331700-88d1-11eb-8c3c-0afebcc7c3f0.png)

Note, I cannot run a full test of this, but did recreate it in my own environment. You may need to install Seaborn if you get an import error, but this is a standard extension library to matplotlib/pyplot.

Please let me know how I can help with this project or if you want some more changes to this!

2021-03-21 19:28 UTC, cdoern requested changes
looks pretty good I tested on my local machine. One issue is that the suplabel is out of the image when you save the plot. I solved this issue by removing the "tight_layout" and "y=1.03" lines and just having it as plt.suptitle('Weekly Voting Data')

2021-03-21 19:28 UTC, cdoern commented on RedditComponent/graph.py
> +    	plt.tight_layout() # Clean Suptitle
remove this line, causes overlap with graph

2021-03-21 19:28 UTC, cdoern commented on RedditComponent/graph.py
> +    	fig.suptitle('Weekly Voting Data', y=1.03)
change to "plt" instead of fig, remove y=1.03. This removes issue of title running into graph as well as the issue of title not appearing in image.

2021-03-21 19:50 UTC, jacobswe commented
Sweet, similarly solvable by adding the bbox_inches='tight' as a plt.savefig parameter to save the entire fig as displayed by plt.show(). Let me know if you want me to add this to the request. Glad to see it works well.

2021-03-21 22:40 UTC, cdoern commented
you seem pretty familiar with the API so whichever is more "correct" you can choose!

2021-03-22 14:35 UTC, jacobswe commented
Should work for you now, also added one to the ymax to give a smidge of padding.

2021-03-22 14:43 UTC, cdoern approved these changes
looks good! just tested it and it saves perfectly

2021-03-22 14:44 UTC, merged